### ISSUE TITLE
Cannot edit user profile info. Password validation fires up

### ISSUE THREAD

**Issue by yigitozkavci** [Mississippi-Governors-School/govschool#15]
When I try to update my profile, `Current password can't be blank` validation prevents me from updating it.

**Comment by Linell** [comment]
That's working as it should be, although it _is_ a little unintuitive. 
![screen shot 2016-10-25 at 7 08 25 am](https://cloud.githubusercontent.com/assets/1231554/19685441/46ea13fc-9a82-11e6-9f04-336f52f374ff.png)

**Comment by yigitozkavci** [comment]
Isn't it wrong to force user to enter his password just to update his information? And that field is on the bottom of the page. It's far more than unintuitive
